version: '3'
services:
  python:
    container_name: cron-python
    build: .
    restart: always
    tty: true
    volumes:
      - '.:/usr/src/app'
      - './root:/var/spool/cron/crontabs/root'
    command: crond -f
